title: Adam Zein Aslam

logo: /assets/img/headshot_circle.png

description: >
  Information Systems Student
  | Data Analyst
  | Data Engineer
  | Data Scientist

show_downloads: false

theme: jekyll-theme-minimal
